# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: MIT

name: Scheduled Publish of ONNX Runtime Execution Provider

permissions:
  checks: write
  contents: read
  id-token: write

on:
  schedule:
    - cron: "0 9 * * *"  # Every day at 2am in San Diego/PDT (9am UTC)

jobs:
  publish-artifacts:
    name: Publish Artifacts
    uses: ./.github/workflows/qualcomm-internal-release.yml
    secrets: inherit
    with:
      nightly_build: true
      skip_publish_qa: false
      skip_publish_wheel: false
      build_windows_arm64_debug: true
      build_windows_arm64_relwithdebinfo: true
